version: "3.2"
services:

  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  php:
    image: php:${PHP_VERSION}-fpm-alpine
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
    depends_on:
      - mysql
    networks:
      - backend

  apache:
    image: httpd:${APACHE_VERSION}-alpine
    networks:
      - backend
    volumes:
      - ./public_html/:/usr/local/apache2/htdocs
      - ./resources/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - mysql
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"

networks:
  frontend:
  backend:
